### ISSUE TITLE
FlxOutlineEffect Produces Incorrect Results

### ISSUE THREAD

**Issue by Ashedragon** [HaxeFlixel/flixel-addons#310] opened 2018-03-22 00:29 UTC
It seems that at some point, this effect just 100% stopped working on the targets that I use (native and neko). Creating an effect like this:
`var outline = new FlxOutlineEffect(FlxOutlineMode.PIXEL_BY_PIXEL, FlxColor.WHITE, 1);`
Produces this.
![screenshot 2018-03-21 20 19 51](https://user-images.githubusercontent.com/6158748/37744440-9190d0ec-2d45-11e8-8ce6-1d66e9d23f60.png)

Previous attempts with NORMAL produced results not dissimilar to this:
![image](https://cdn.discordapp.com/attachments/162664383082790912/238813031595900929/unknown.png)
or this
![screenshot 2018-03-21 20 26 58](https://user-images.githubusercontent.com/6158748/37744565-3a8491f2-2d46-11e8-9616-e31ee7bd790a.png)

I'm running Windows 10 (64-bit) with an AMD Radeon 270x, though this happened on my Windows 7 (64-bit) install, my other 64-bit Windows 10 on my laptop and a 32-bit Windows 8 on another laptop. I reproduced this effect on my Linux distro tests (Elementary OS, Ubuntu and Mint, all 64-bit) as well.

**Comment by Gama11** [comment] 2018-03-22 01:15
I can't reproduce the issue where the entire rectangle is filled with the outline color. No difference between OpenFL Next and Legacy. This looks good to me:

![](https://i.imgur.com/0B4Sk6B.png)

```haxe
package;

import flixel.FlxState;
import flixel.FlxSprite;
import flixel.util.FlxColor;
import flixel.addons.effects.chainable.FlxEffectSprite;
import flixel.addons.effects.chainable.FlxOutlineEffect;

class PlayState extends FlxState
{
    override public function create():Void
    {
        bgColor = FlxColor.GRAY;
        var sprite = new FlxSprite(AssetPaths.pyramid__png);
        var outline = new FlxOutlineEffect(FlxOutlineMode.PIXEL_BY_PIXEL, FlxColor.WHITE, 3);
        add(new FlxEffectSprite(sprite, [outline]));
    }
}

```

[Source Image](https://i.imgur.com/hVJ0DvD.png)

Also, not sure what's wrong in your first picture?

**Comment by Ashedragon** [comment] 2018-03-22 02:50
Apologies, I should have clarified. It doesn't seem to make the outline the right size at all. So instead of completely surrounding the sprite, it just shows in the top left. Using your image:
![screenshot 2018-03-21 22 48 03](https://user-images.githubusercontent.com/6158748/37748372-f9bb1740-2d59-11e8-820e-4c7d011052e1.png)

And then if I switch the FlxOutlineMode to NORMAL...
![screenshot 2018-03-21 22 48 59](https://user-images.githubusercontent.com/6158748/37748412-16e8209c-2d5a-11e8-8de0-4368b7d7f69c.png)

`var sprite = new FlxSprite(0, 0, AssetPaths.hVJ0DvD__png);
var outline = new FlxOutlineEffect(FlxOutlineMode.NORMAL, FlxColor.WHITE, 1);
add(new FlxEffectSprite(sprite, [outline]));`

**Comment by Gama11** [comment] 2018-03-22 10:37
Huh, it seems OpenFL Next and Legacy behave differently after all, I must have made a mistake when testing earlier. `FlxOutlineEffect` uses the same code on all targets, and it works correctly on Flash, so it seems likely that this is a bug with some OpenFL API.

OpenFL 8 seems to work correctly (this is on Neko with `NORMAL`):

![](https://i.imgur.com/XiaS8HJ.png)

Luckily official support for that isn't too far off anymore. :) You could try https://github.com/HaxeFlixel/flixel/pull/2136.

**Comment by Ashedragon** [comment] 2018-03-27 20:22
I tried it and all it seems to do is cut my FPS in half on both neko and cpp. The outline remains the same?

**Comment by Gama11** [comment] 2018-03-27 20:30
With OpenFL 8? That's not what I'm seeing... What's the exact code you're running?

**Comment by Ashedragon** [comment] 2018-03-29 16:54
I take that back, PIXEL_BY_PIXEL doesn't work, but NORMAL seems to work fine. However, it still cuts my FPS in half.

**Comment by Gama11** [comment] 2018-03-29 17:15
By "doesn't work", do you mean it's not completely surrounding the sprite like you mentioned earlier?

![](https://i.imgur.com/BYyukg5.png)

If so, that seems expected.. or, well, consistent with Flash at least, which indicates OpenFL isn't at fault.

I also had some FPS issues, but they seemed to affect HaxeFlixel games in general, not just with OpenFL 8.. Does `vsync="false"` make a difference? (there should be a `vsync="true"` in your `Project.xml` by default)

**Comment by Gama11** [comment] 2018-03-29 18:45
I'm assuming you're testing Neko? Neko performance is worse in OpenFL 8 (and not much to be done about that), but Cpp should be about the same and HTML5 much faster.

**Comment by Gama11** [comment] 2018-04-21 21:44
I think this can be closed now that OpenFL 8 support has been merged (https://github.com/HaxeFlixel/flixel/pull/2136). I checked the results again any they look good to me / consistent with Flash.

**Closed by Gama11** 2018-04-21 21:44 UTC
