### ISSUE TITLE
[Next] FlxScreenGrab

### ISSUE THREAD

**Issue by SARFEX** [HaxeFlixel/flixel-addons#231] opened 2016-02-24 00:13 UTC
Related to https://github.com/HaxeFlixel/flixel/issues/1708 

I tried myself several times to realize it, but my knowledge and experience is not enough.
Maybe it will not take much time from a professional? I would be very grateful.
Thank you

**Comment by GimmickyApps** [comment] 2016-02-26 18:20
I just tried `FlxScreenGrab.grab(null, true, true);` on a windows release build, and nothing appeared to happen.  At least, no save dialog came up.  I could definitely use this feature right now, because I have many sprites on the screen that never change, and need to just take a simple full-screen screenshot to use as a pre-rendered background, and then I can cut down on the number of sprites by about 90% which certainly makes my game less laggy.

**Comment by Gama11** [comment] 2016-02-26 18:55
No save dialog popping up may very well be caused by my workaround for https://github.com/HaxeFlixel/flixel-addons/issues/222. That doesn't necessarily mean it didn't work.

**Comment by SARFEX** [comment] 2016-02-26 19:02
@GimmickyApps, You use "Next"? For Legacy and other targets FlxScreenGrab works fine

**Comment by GimmickyApps** [comment] 2016-02-26 19:05
I'm not sure, actually.  I don't see mention of either one in my Project.xml, which was based on the basic template.  How do I find out for sure?

**Comment by Gama11** [comment] 2016-02-26 19:11
If you haven't actively switched to next, you're using legacy, since Flixel defaults to that.

**Comment by SARFEX** [comment] 2016-02-26 19:12
If your project.xml does not contain 
`<set name="next" />`
And you do not use -Dnext  to compile like "lime build windows -release -Dnext", you are using legacy, and you can easy capture images from screen

**Comment by SARFEX** [comment] 2016-02-26 19:23
Try to reproduce that I wrote here :) https://github.com/HaxeFlixel/flixel/issues/1708

**Comment by GimmickyApps** [comment] 2016-02-27 06:58
@SARFEX thanks, but in 1708 it sounds like it was already reproduced and figured out?

**Comment by SARFEX** [comment] 2016-02-27 07:00
@GimmickyApps it works when you reproduce on Legacy, problems only on Next

**Comment by GimmickyApps** [comment] 2016-02-27 07:09
Right, but Gama11 found something you could disable so that it works on Next.  Why do you need more people to reproduce it still?  (I'm not likely to have any explanatory depth to offer beyond Gama11 :) )

**Comment by GimmickyApps** [comment] 2016-02-27 07:12
Oh, I see, you meant as a way to figure out whether I'm using next or not!  Well, I think your and Gama11's explanations are sufficient.   I don't have the setting in the xml, and I just verified that FlashDevelop is not adding "-Dnext" when it runs the compiler, so I think it's safe to say I'm on legacy.

**Comment by SARFEX** [comment] 2016-03-09 06:48
I am very close to the _first-public-pre-alpha-wtf-omg_ version of my game, 
It's simple, but I'm very much time on that, and plans go to Steam and mobiles.

Screen grabbing feature is not main part of the game, but I want to have it in the first preview version. :<

I will add the name who will help me in the credits (I can't do more now), when I finish it.
Plz help

**Comment by GimmickyApps** [comment] 2016-03-09 07:04
@Gama11 mentioned that it may have worked, minus the save dialog.  Is there a possible workaround just dumping to a directory with -01, -02, etc. suffixes, sans dialog?

**Comment by SARFEX** [comment] 2016-03-09 07:10
i don't need dialogs. I use Next in which BitmapData.draw(Lib.current.stage) not working properly on windows targets

**Comment by IBwWG** [comment] 2016-06-22 11:18
"BitmapData.draw(Lib.current.stage) not working properly on windows targets" -- do you have a reference for this (i.e. link to another issue)?  What's broken exactly in Next?

**Comment by Gama11** [comment] 2018-04-21 22:35
This seems like a duplicate of #82.

**Closed by Gama11** 2018-04-21 22:35 UTC
